account_id = "c2213d59c49c3fe4a2c6d09be737889e"
name = "cf-worker-status-page-pro"
main = "./src/worker/index.ts"
compatibility_flags = [ "streams_enable_constructors" ]
compatibility_date = "2021-09-29"
workers_dev = true
# npx --no -- wrangler kv:namespace create cf-worker-status-page-pro
kv_namespaces = [ { binding = "KV_STORE", id = "6c90bb2ca3d341368cc9751d6de8ba0d" } ]

[site]
bucket = "./dist/client"

[dev]
port = 3000

[env.production]
kv_namespaces = [ { binding = "KV_STORE", id = "6c90bb2ca3d341368cc9751d6de8ba0d" } ]

[env.production.triggers]
# https://ittools.yuricunha.com/crontab-generator <- reference cron
# https://crontab.guru/#0_*/6_*_*_* <- for reference
# https://crontab.cronhub.io/ <- for reference
crons = [ "0 */6 * * *" ]
