account_id = "0db3c9ec1d741afb9a63eab399c77c3b"
name = "cf-worker-status-page-pro"
main = "./src/worker/index.ts"
compatibility_flags = [ "streams_enable_constructors" ]
compatibility_date = "2021-09-29"
workers_dev = true
# npx --no -- wrangler kv:namespace create cf-worker-status-page-pro
kv_namespaces = [ { binding = "KV_STORE", id = "c2213d59c49c3fe4a2c6d09be737889e" } ]

[site]
bucket = "./dist/client"

[dev]
port = 3000

[env.production]
kv_namespaces = [ { binding = "KV_STORE", id = "c2213d59c49c3fe4a2c6d09be737889e" } ]

[env.production.triggers]
# https://crontab.guru/#*/2_*_*_*_*
crons = [ "*/2 * * * *" ]
